

// ** user data
export const SET_USER_DATA="SET_USER_DATA";

//**  cars action types
export const GET_CAR_TYPES = "GET_CAR_TYPES";
export const GET_CAR_TYPES_SUCCESS = "GET_CAR_TYPES_SUCCESS";
export const GET_CAR_TYPES_FAILURE = "GET_CAR_TYPES_FAILURE";

export const SELECTED_CAR_TYPE="SELECTED_CAR_TYPE";
export const SELECTED_CAR_BRAND="SELECTED_CAR_BRAND";


//**  get insurance company 
export const GET_INSURANCE_COMPANIES = "GET_INSURANCE_COMPANIES";
export const GET_INSURANCE_COMPANIES_SUCCESS = "GET_INSURANCE_COMPANIES_SUCCESS";
export const GET_INSURANCE_COMPANIES_FAILURE = "GET_INSURANCE_COMPANIES_FAILURE";

export const SELECTED_LAST_INSURANCE="SELECTED_LAST_INSURANCE";

//**  get  third discount
export const GET_THIRD_DISCOUNT = "GET_THIRD_DISCOUNT";
export const GET_THIRD_DISCOUNT_SUCCESS = "GET_THIRD_DISCOUNT_SUCCESS";
export const GET_THIRD_DISCOUNT_FAILURE = "GET_THIRD_DISCOUNT_FAILURE";

export const SELECTED_THIRD_DISCOUNT="SELECTED_THIRD_DISCOUNT";


//**  driver discount getDriverDiscount
export const GET_DRIVER_DISCOUNT = "GET_DRIVER_DISCOUNT";
export const GET_DRIVER_DISCOUNT_SUCCESS = "GET_DRIVER_DISCOUNT_SUCCESS";
export const GET_DRIVER_DISCOUNT_FAILURE = "GET_DRIVER_DISCOUNT_FAILURE";

export const SELECTED_DRIVER_DISCOUNT="SELECTED_DRIVER_DISCOUNT";